#!/usr/bin/sh

DIRECTORY="$HOME/.config/flatpak-local-script"
REPO_PATH="$HOME/Projects/flatpak/repo"

if [[ ! -d "$DIRECTORY" ]]
then
    mkdir -p $DIRECTORY
fi

run() { # $1 = alias to program
    PROGRAM_FULL_NAME=$(cat $DIRECTORY/$1)
    PROGRAM_NAME=${PROGRAM_FULL_NAME::-5} #rewrite that
    flatpak-builder --repo=$REPO_PATH --force-clean --ccache --state-dir=$HOME/flatpak/Projects/state-dir/$PROGRAM_NAME build-dir $PROGRAM_FULL_NAME -y
    flatpak remote-add --if-not-exists --no-gpg-verify local-repo $REPO_PATH
    flatpak install $PROGRAM_NAME -y
    flatpak run $PROGRAM_NAME
}

create() {
    FILE="$DIRECTORY/$1"
    if [[ -f $FILE ]]; then
        echo "Config file $FILE is already exists."
        exit 1
    fi
    echo $2 >> $FILE
}

update() {
    PROGRAM_FULL_NAME=$(cat $DIRECTORY/$1)
    PROGRAM_NAME=${PROGRAM_FULL_NAME::-5} #rewrite that
    flatpak-builder --repo=$REPO_PATH --force-clean --ccache --state-dir=$HOME/Projects/flatpak/state-dir/$PROGRAM_NAME build-dir $PROGRAM_FULL_NAME -y
    flatpak update $PROGRAM_NAME -y
    flatpak run $PROGRAM_NAME
}

show_help() {
    echo "This is help message"
}

if [[ $1 == "run" ]]; then
    if [[ -z "$2" ]]; then
        echo "Please add name to run"
        exit 1
    fi
    run $2
    exit 0
elif [[ $1 == "create" ]]; then
    if [[ -z "$2" ]]; then
        echo "No new name found"
        exit 1
    elif [[ -z "$3" ]]; then
        echo "No filename provided"
        exit 1
    fi
    create "$2" "$3"
    exit 0
elif [[ $1 == "update" ]]; then
    if [[ -z "$2" ]]; then
        echo "No new name found"
        exit 1
    fi
    update "$2"
    exit 0
elif [[ $1 == "--help" ]]; then
    show_help
else
    show_help
fi